### ISSUE TITLE
Compile Help

### ISSUE THREAD

**Issue by Pai-Po** [tandasat/FU_Hypervisor#1]
Hi, i'm compiling you project and i get some error:
**C++ exception handling is not supported with /kernel**。
Can you tell me something about how to use stl eg. **std::array** when writing kernel driver。
I compile it using VS2015 & WDK10.0 。Thanks 。

**Comment by tandasat** [comment]
Hi, I do not support this project, but you can try those instructions:
http://tandasat.github.io/HyperPlatform/userdocument/#__RefHeading___Toc906_1354011707

Please re-open the ticket if this does not help. Thanks.

**Comment by Pai-Po** [comment]
Many thanks。But i have some confusion，does all stl libray work correctly?  Have you ever occasionally got some unsupported situation?

**Comment by tandasat** [comment]
The use of STL is merely for faster prototyping, and I do not believe all part of STL work correctly (if it does, it should have been supported by Microsoft). Some might not compile and some might trigger unexpected runtime behaviour. 

I personally have not seen any issues with the very limited use of STL in the kernel, but I guess exception would cause an issue (I do not remember what STL does when `_HAS_EXCEPTIONS` is zero).

**Comment by Pai-Po** [comment]
i get it。thanks。
