### ISSUE TITLE
is it a complete project?

### ISSUE THREAD

**Issue by pavilionng0002** [tandasat/FU_Hypervisor#2]
I saw FpVmCallCreateFakePage in fake_page.cpp, but it has no vmcall number in the function 
 of VmmpHandleVmCall.

**Comment by tandasat** [comment]
I do not actively support this project. But you are probably not checking out submodule (HyperPlatform) correctly. This is what you should be getting: https://github.com/tandasat/HyperPlatform/blob/36816f07b6574f360e34e82e87d53b6b934cd6ad/HyperPlatform/vmm.cpp#L1050

Try `git clone --recursive https://github.com/tandasat/FU_Hypervisor.git`.
